name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CLOUDFLARE_ENV: production
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build
        run: pnpm exec opennextjs-cloudflare build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
